version: '3'
services:
  servo:
    image: vtxteam/servo:latest
    links:
      - "mongodb"
    volumes:
      - ./user.json:/work/user.json
      - ./upload:/work/upload
    ports:
      - "9000:9000"
    depends_on:
      - "mongodb"
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=W4FnTL0XRB9yzE6lB7uoZu7M
    restart: on-failure
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./data/mongodb:/data/db
